import { useState, useEffect, useRef } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { getMetadata } from "../functions/getMetadata"
import { getPlaylist } from "../functions/getPlaylist"
import { getNextTrack } from "../functions/getNextTrack"

interface TrackProps {
  id: string            //"2xplsy2dll8pouy"
  name: string          //"Alice In Chains - Man In The Box"
  index: number         //0
  currentTime: number   //242.34 (seconds)
}

interface AlbumProps {
  title: string         //"The Works"
  artist: string        //"Queen"
  year: string          //"1984"
  image: string         //"https://rovimusic.rovicorp.com/image.jpg?c=YD1cN-_cz484qf9RigYGpphUoDg0hsvx4F4sL4oO-nA=&f=2"
}

export default function Home() {

  // **********
  // Constants
  // **********

  const [ playlist, setPlaylist] = useState<string[]>([])
  
  const [ track, setTrack ] = useState<TrackProps>({
    id: '',
    name: '',
    index: -1,
    currentTime: 0
  })

  const [ album, setAlbum ] = useState<AlbumProps>({
    title: '',
    artist: '',
    year: '',
    image: ''
  })
  
  //V1 - Audio Object
  //let audio = new Audio() object
  //const [ audio ] = useState(new Audio())
  //V2 - reference to html audio element
  const audioRef = useRef<HTMLAudioElement>(null)

  // **********
  // useEffects
  // **********
  
  useEffect(() => {
    if (playlist.length === 0) {
      getPlaylist()
      .then(playlist => {
        setPlaylist(playlist)
      })
    }
  }, [])

  // I can't use addEventListeners here,
  // they call console.log a billion times
  //audio.addEventListener('canplaythrough', () => {...}

  useEffect(() => {

    // I can't use addEventListeners here,
    // they save an instance of the useState vars and don't update those values
    //audio.addEventListener('canplaythrough', () => {...}

    if (playlist.length > 0) {
      const nextTrack = getNextTrack(playlist, track.index)
      setTrack(nextTrack)
    }

  }, [playlist])

  useEffect(() => {
    
    //Add function "Listener1" to event "canplaythrough":
    audioRef.current!.addEventListener("canplaythrough", function L1() {

      audioRef.current!.removeEventListener("canplaythrough", L1) //remove to re-attach later and get the updated useState vars

      //V1 - Audio obj
      //audio.currentTime = audio.duration - 5    //dev: set track 'n' secs before finish
      //audio.play()

      //V2 - audioRef
      //audioRef.current!.currentTime = audioRef.current!.duration - 5                //dev: set track 'n' secs before finish
      audioRef.current!.currentTime = audioRef.current!.duration * track.currentTime  //prod
      audioRef.current?.play()
    })

    //Add function "Listener2" to event "ended":
    audioRef.current!.addEventListener("ended", function L2() {
      
      audioRef.current!.removeEventListener("ended", L2)        //remove to re-attach later and get the updated useState vars
      
      if (playlist.length > 0) {
        const nextTrack = getNextTrack(playlist, track.index)
        setTrack(nextTrack)
      }
    })

    //Load audio to the HTML component
    if (track.name) {
      //V1 - dev
      //let url = "https://www.dropbox.com/s/h8278j0vncmdsrp/Airbourne%20-%20Its%20All%20For%20Rock%20N%20Roll.mp3"
      //url = url.replace('www.dropbox.com', 'dl.dropboxusercontent.com')
      //audio.src = url
      //V1 - prod
      //const url = `https://dl.dropboxusercontent.com/s/${track?.id}/${track?.name.replace(/ /g, "%20")}`
      //audio.src = url

      //V2
      audioRef.current?.load()

      console.log(`Loading track ${track.index}: ${track.name}`)
    }

    //Update state with audio data
    setAlbum({title: '', artist: '', year: '', image: ''})
    getMetadata({fileId: track.id, fileName: track.name})
    .then( ({title, artist, year, image}) => {
      if (track.name) {
        setAlbum({ title, artist, year, image })
      }
    })

  }, [track])

  // **********
  // HTML
  // **********
  
  return (
    <div className={styles.main}>

      <Head>
        <title>Ale FM - A Melhor!</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <p>
        Você está ouvindo a {" "}
        <a className={styles.link} href="https://github.com/Alessandro1918/aleFM" target="_blank">Ale FM</a>
        , a melhor!
      </p>

      <div>
        {/* I think this check is faster than the async setState. Will render spinning albumCover @ production: */}
        {/* {
          album.image === ''
          ? <img src="/logo.svg" className={styles.albumArtPlaceholder} alt="logo" />
          : <img src={album.image} className={styles.albumArt} alt="album-art" />
        } */}
        {/* This double check provides time to clear the previous albumArt, display the spinnigAtom, and display the new (frozen) albumCover */}
        {
          album.image === '' &&
          <img src="/logo.svg" className={styles.albumArtPlaceholder} alt="logo" />
        }
        {
          album.image !== '' &&
          <img src={album.image} className={styles.albumArt} alt="album-art" />
        }
      </div>

      {track.name
        ? <p>{track.name}</p>
        : <p>Carregando...</p>
      }

      {album.title && album.year
        && <p>{`do álbum: ${album.title} (${album.year})`}</p>
      }

      <audio ref={audioRef} controls>
        <source 
          src={`https://dl.dropboxusercontent.com/s/${track.id}/${track.name.replace(/ /g, "%20")}`}
          type="audio/mp3"
        />
      </audio>

      {/** V1 - No graphic elements */}
      {/** V2 */}
      <p className={styles.playHint}>
        (Clique em ▶ para iniciar a reprodução)
      </p>

      {/* <div 
        className={styles.radioGroup} 
        onChange={() => setIsAlbumDataFromApi(!isAlbumDataFromApi)}
      >
        <label>Informações: </label>
        <label title="Informações da música vindas de uma API customizada">
          <input type="radio" checked={isAlbumDataFromApi} /> 
          API&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(?)
        </label>
        <label title="Informações da música vindas direto do arquivo">
          <input type="radio" checked={!isAlbumDataFromApi} /> 
          Metadados&nbsp;(?)
        </label>
      </div> */}

    </div>
  )
}
